# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'mab' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mab
  pod 'FMDB'
  pod 'MBProgressHUD'
  pod 'SwiftDate'
  pod 'CryptoSwift'
  pod 'HandyJSON'
  pod 'AlamofireImage'
  
end
